### PR TITLE
Add gripper model for dxl_7dof_arm

### PR DESCRIPTION
**Pull request by tongtybj**
The gripper CAD model is added in [dynamixel_urdf](https://github.com/dgossow/dynamixel_urdf)
Please check: https://github.com/jsk-enshu/dynamixel_urdf/pull/1

screenshot from 2018-09-03 06-09-14
screenshot from 2018-09-03 06-08-16

### CODE REVIEW

**Comment by tongtybj** [comment]
Please try following command to check the robot model in gazebo and rviz.

```
$ roslaunch dxl_armed_turtlebot dxl_armed_turtlebot_gazebo.launch
```

**Comment by tongtybj** [comment]
@k-okada @yuki-asano 

このPRをマージしていただけると、その後の作業が捗ります。
あと、マージ権限の付与は検討していただけると助かります。

**Comment by YutoUchimi** [comment]
Worked on my environment!

**Comment by Affonso-Gui** [comment]
Also commented a bit on the PR, but if we are only using one repository now maybe we can change from `wstool` to `git clone` ?
```
$ cd ~/catkin_ws 
$ wstool init src
$ wstool set robot-programming https://github.com/jsk-enshu/robot-programming --git -t src
$ wstool update -t src
```
to
```
$ cd ~/catkin_ws/src 
$ git clone https://github.com/jsk-enshu/robot-programming.git
```

**Comment by tongtybj** [comment]
@Affonso-Gui 

Thanks for your debug.

**Pull request merged**
