### PR TITLE
Armed turtlebot in  Gazebo

### PR DESCRIPTION
**Pull request by tongtybj**
Please check  [README.md](https://github.com/tongtybj/robot-programming/blob/gazebo/dxl_armed_turtlebot/README.md)

### CODE REVIEW

**Comment by YutoUchimi** [comment]
### Not working on indigo?

OK:
- Ubuntu 16.04 + kinetic
- gazebo 7.14.0-1~xenial

Error:
- Ubuntu 14.04 + indigo
- gazebo 2.2.6-1~trusty

When executing `roslaunch dxl_armed_turtlebot dxl_armed_turtlebot_gazebo.launch` on indigo environment, I faced the following error message.

```
Error [parser.cc:697] XML Element[surface], child of element[link] not defined in SDF. Ignoring.[link]
Error [parser.cc:688] Error reading element <link>
Error [parser.cc:688] Error reading element <model>
Error [parser.cc:688] Error reading element <world>
Error [parser.cc:348] Unable to read element <sdf>
Error:   Could not find the 'robot' element in the xml file
         at line 81 in /build/buildd/urdfdom-0.2.10+dfsg/urdf_parser/src/model.cpp
Error [parser_urdf.cc:2608] Unable to call parseURDF on robot model
Error [parser.cc:273] parse as old deprecated model file failed.
Error [Server.cc:300] Unable to read sdf file[/home/yuto/Projects/enshu/src/robot-programming/dxl_armed_turtlebot/worlds/empty.world]
gzserver: /usr/include/boost/thread/pthread/recursive_mutex.hpp:101: boost::recursive_mutex::~recursive_mutex(): Assertion `!pthread_mutex_destroy(&m)' failed.
Aborted
[gazebo-5] process has died [pid 18164, exit code 134, cmd /opt/ros/indigo/lib/gazebo_ros/gzserver -e ode /home/yuto/Projects/enshu/src/robot-programming/dxl_armed_turtlebot/worlds/empty.world __name:=gazebo __log:=/home/yuto/.ros/log/89a74860-df4d-11e8-b18f-b808cf4bd6aa/gazebo-5.log].
log file: /home/yuto/.ros/log/89a74860-df4d-11e8-b18f-b808cf4bd6aa/gazebo-5*.log
```

This error disappears when I comment out `surface` tag in `empty.world` (https://github.com/jsk-enshu/robot-programming/blob/f5881faaf2476bc46924f26a5f028efda35668c1/dxl_armed_turtlebot/worlds/empty.world#L326-L333)
```
        <surface>
          <friction>
            <ode>
              <mu>0.4</mu>
              <mu2>0.4</mu2>
            </ode>
          </friction>
        </surface>
```

**Comment by tongtybj** [comment]
This is quite confusing...
There is the same description in the next model part:
https://github.com/jsk-enshu/robot-programming/blob/f5881faaf2476bc46924f26a5f028efda35668c1/dxl_armed_turtlebot/worlds/empty.world#L369-L376

Is there any difference between these two model description?

**Comment by tongtybj** [comment]
@YutoUchimi 

By the way, have you tried the gazebo samples introduced in [README.md](https://github.com/tongtybj/robot-programming/blob/gazebo/dxl_armed_turtlebot/README.md)?
Please  try them and confirm the expected motion.

**Comment by YutoUchimi** [comment]
Sorry, I forgot to paste the latter lines (L369-L376).
I commented out both of them (L326-L333 and L369-L376), and then it worked on indigo environment.

---

- [x] 1. Grasping test in gazebo via roseus
- [x] 2. Object recognition and approaching via roseus
- [x] 3. SLAM in Gazebo
- [x] 4. Detect Checkerboard in Gazebo

**Comment by tongtybj** [comment]
@YutoUchimi 

I found the same problem in 16.04, but it is warnning:
```
Warning [parser.cc:778] XML Element[surface], child of element[link] not defined in SDF. Ignoring[surface]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
Warning [parser.cc:778] XML Element[surface], child of element[link] not defined in SDF. Ignoring[surface]. You may have an incorrect SDF file, or an sdformat version that doesn't support this element.
```

The reason is that `<surface>` should be inside the parent tag `<collsion>`, but not `<link>`.

I have fixed this bug, please check when you have time.

**Comment by tongtybj** [comment]
@k-okada 

Do we need to add the instruction about how to use gazebo in our text?

**Pull request merged**
